export const LOGIN = "LOGIN";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const GET_USER_INFO = "GET_USER_INFO";
export const FETCHED_USER_INFO = "FETCHED_USER_INFO";
export const GET_OTHER_USER_INFO = "GET_OTHER_USER_INFO";
export const FETHCED_OTHER_USER_INFO = "FETHCED_OTHER_USER_INFO";

export const GET_USER_PUBLICATIONS = "GET_USER_PUBLICATIONS";
export const FETCHING_USER_PUBLICATIONS = "FETCHING_USER_PUBLICATIONS";
export const FETCHED_USER_PUBLICATIONS = "FETCHED_USER_PUBLICATIONS";
export const NO_MORE_USER_PUBLICATIONS = "NO_MORE_USER_PUBLICATIONS";
export const CLEAR_USER_PUBLICATIONS = "CLEAR_USER_PUBLICATIONS";
export const FETCHED_USER_PUBLICATIONS_ON_SCROLLING =
  "FETCHED_USER_PUBLICATIONS_ON_SCROLLING";

export const GET_OTHER_USER_PUBLICATIONS = "GET_OTHER_USER_PUBLICATIONS";
export const FETCHING_OTHER_USER_PUBLICATIONS =
  "FETCHING_OTHER_USER_PUBLICATIONS";
export const FETCHED_OTHER_USER_PUBLICATIONS =
  "FETCHED_OTHER_USER_PUBLICATIONS";
export const NO_MORE_OTHER_USER_PUBLICATIONS =
  "NO_MORE_OTHER_USER_PUBLICATIONS";
export const CLEAR_OTHER_USER_PUBLICATIONS = "CLEAR_OTHER_USER_PUBLICATIONS";
export const FETCHED_OTHER_USER_PUBLICATIONS_ON_SCROLLING =
  "FETCHED_OTHER_USER_PUBLICATIONS_ON_SCROLLING";

export const GET_WORK_TYPES = "GET_WORK_TYPES";
export const FETCHED_WORK_TYPES = "FETCHED_WORK_TYPES";

export const GET_ACCESS_TYPES = "GET_ACCESS_TYPES";
export const FETCHED_ACCESS_TYPES = "FETCHED_ACCESS_TYPES";

export const GET_USER_FOLLOWERS = "GET_USER_FOLLOWERS";
export const FETCHED_USER_FOLLOWERS = "FETCHED_USER_FOLLOWERS";

export const GET_PARTNERS = "GET_PARTNERS";
export const FETCHED_USER_PARTNERS = "FETCHED_USER_PARTNERS";

export const PROMOTE_PUBLICATION = "PROMOTE_PUBLICATION";
export const LIKE_PUBLICATION = "LIKE_PUBLICATION";
export const POST_PUBLICATION = "POST_PUBLICATION";
export const POSTED_PUBLICATION = "POSTED_PUBLICATION";
export const FETCH_LIKED_USERS = "FETCH_LIKED_USERS";
export const FETCH_PROMOTED_USERS = "FETCH_PROMOTED_USERS";
export const FETCHING_LIKED_USERS = "FETCHING_LIKED_USERS";
export const FETCHING_PROMOTED_USERS = "FETCHING_PROMOTED_USERS";
export const FETCHED_LIKED_USERS = "FETCHED_LIKED_USERS";
export const FETCHED_PROMOTED_USERS = "FETCHED_PROMOTED_USERS";
export const NO_MORE_LIKED_USERS = "NO_MORE_LIKED_USERS";
export const NO_MORE_PROMOTED_USERS = "NO_MORE_PROMOTED_USERS";
export const CLEAR_LIKED_USERS = "CLEAR_LIKED_USERS";
export const CLEAR_PROMOTED_USERS = "CLEAR_PROMOTED_USERS";
export const ERROR_OCCUR = "ERROR_OCCUR";

export const GET_INFLUENTIAL_MEMBERS = " GET_INFLUENTIAL_MEMBERS";
export const FETCHED_INFLUENTIAL_MEMBERS = " FETCHED_INFLUENTIAL_MEMBERS";
export const INFLUENTIAL_MEMBERS_CLEAR = "INFULENTIAL_MEMBERS_CLEAR";
